package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Структура для хранения информации о пакете
type pkgInfo struct {
	path    string
	name    string
	files   []string
	structs []structInfo
}

// Структура для хранения информации о структуре
type structInfo struct {
	name   string
	fields []fieldInfo
	file   string // файл, где объявлена структура
}

// Информация о поле структуры
type fieldInfo struct {
	name string
	typ  ast.Expr
}

func main() {
	// Начинаем сканирование с текущей директории
	root, err := os.Getwd()
	if err != nil {
		fmt.Printf("Ошибка получения текущей директории: %v\n", err)
		os.Exit(1)
	}

	if err := generateResetFunctions(root); err != nil {
		fmt.Printf("Ошибка генерации: %v\n", err)
		os.Exit(1)
	}
}

func generateResetFunctions(root string) error {
	// Собираем информацию обо всех пакетах
	packages := make(map[string]*pkgInfo)

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Пропускаем скрытые директории и vendor
		if d.IsDir() && (strings.HasPrefix(d.Name(), ".") || d.Name() == "vendor") {
			return fs.SkipDir
		}

		// Ищем Go файлы
		if !d.IsDir() && strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			dir := filepath.Dir(path)
			if packages[dir] == nil {
				packages[dir] = &pkgInfo{
					path:  dir,
					files: []string{path},
				}
			} else {
				packages[dir].files = append(packages[dir].files, path)
			}
		}

		return nil
	})

	if err != nil {
		return fmt.Errorf("ошибка обхода директорий: %w", err)
	}

	// Анализируем каждый пакет
	for _, pkg := range packages {
		if err := analyzePackage(pkg); err != nil {
			return fmt.Errorf("ошибка анализа пакета %s: %w", pkg.path, err)
		}
	}

	// Генерируем reset.gen.go для пакетов, где найдены структуры
	for _, pkg := range packages {
		if len(pkg.structs) > 0 {
			if err := generateResetFile(pkg); err != nil {
				return fmt.Errorf("ошибка генерации файла для %s: %w", pkg.path, err)
			}
		}
	}

	return nil
}

func analyzePackage(pkg *pkgInfo) error {
	fset := token.NewFileSet()

	for _, filePath := range pkg.files {
		// Парсим файл
		file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("ошибка парсинга файла %s: %w", filePath, err)
		}

		// Сохраняем имя пакета
		if pkg.name == "" {
			pkg.name = file.Name.Name
		}

		// Ищем структуры с комментарием // generate:reset
		ast.Inspect(file, func(n ast.Node) bool {
			if decl, ok := n.(*ast.GenDecl); ok && decl.Tok == token.TYPE {
				// Проверяем комментарии
				hasResetComment := false
				if decl.Doc != nil {
					for _, comment := range decl.Doc.List {
						if strings.TrimSpace(comment.Text) == "// generate:reset" {
							hasResetComment = true
							break
						}
					}
				}

				if hasResetComment {
					for _, spec := range decl.Specs {
						if typeSpec, ok := spec.(*ast.TypeSpec); ok {
							if structType, ok := typeSpec.Type.(*ast.StructType); ok {
								// Собираем информацию о полях
								var fields []fieldInfo
								for _, field := range structType.Fields.List {
									for _, name := range field.Names {
										fields = append(fields, fieldInfo{
											name: name.Name,
											typ:  field.Type,
										})
									}
									// Обрабатываем анонимные поля
									if len(field.Names) == 0 {
										fields = append(fields, fieldInfo{
											name: getTypeName(field.Type),
											typ:  field.Type,
										})
									}
								}

								pkg.structs = append(pkg.structs, structInfo{
									name:   typeSpec.Name.Name,
									fields: fields,
									file:   filePath,
								})
							}
						}
					}
				}
			}
			return true
		})
	}

	return nil
}

func getTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + getTypeName(t.X)
	case *ast.SelectorExpr:
		// Для импортированных типов возвращаем только имя селектора
		// например, для "time.Time" -> "Time"
		return t.Sel.Name
	case *ast.ArrayType:
		return "[]" + getTypeName(t.Elt)
	case *ast.MapType:
		return "map[" + getTypeName(t.Key) + "]" + getTypeName(t.Value)
	default:
		return fmt.Sprintf("%T", t)
	}
}

func generateResetFile(pkg *pkgInfo) error {
	var buf bytes.Buffer

	// Заголовок файла
	buf.WriteString("// Code generated by reset tool. DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package " + pkg.name + "\n")
	buf.WriteString("\n")

	// Генерируем методы Reset для каждой структуры
	for _, structInfo := range pkg.structs {
		buf.WriteString(generateResetMethod(structInfo))
		buf.WriteString("\n")
	}

	// Форматируем код
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("ошибка форматирования кода: %w\nИсходный код:\n%s", err, buf.String())
	}

	// Записываем файл
	outputPath := filepath.Join(pkg.path, "reset.gen.go")
	return os.WriteFile(outputPath, formatted, 0644)
}

func generateResetMethod(info structInfo) string {
	var buf strings.Builder

	// Сигнатура метода
	receiver := strings.ToLower(string(info.name[0]))
	buf.WriteString(fmt.Sprintf("func (%s *%s) Reset() {\n", receiver, info.name))
	buf.WriteString(fmt.Sprintf("    if %s == nil {\n", receiver))
	buf.WriteString("        return\n")
	buf.WriteString("    }\n\n")

	// Генерируем сброс для каждого поля
	for _, field := range info.fields {
		generateFieldReset(&buf, receiver, field)
	}

	buf.WriteString("}\n")
	return buf.String()
}

func generateFieldReset(buf *strings.Builder, receiver string, field fieldInfo) {
	fieldAccess := receiver + "." + field.name

	switch expr := field.typ.(type) {
	case *ast.Ident:
		// Базовые типы
		switch expr.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128":
			fmt.Fprintf(buf, "    %s = 0\n", fieldAccess)
		case "string":
			fmt.Fprintf(buf, "    %s = \"\"\n", fieldAccess)
		case "bool":
			fmt.Fprintf(buf, "    %s = false\n", fieldAccess)
		case "byte", "rune":
			fmt.Fprintf(buf, "    %s = 0\n", fieldAccess)
		default:
			// Предполагаем, что это пользовательский тип структуры
			// Проверяем, есть ли у него метод Reset
			fmt.Fprintf(buf, "    if resetter, ok := interface{ Reset() }(%s); ok {\n", fieldAccess)
			fmt.Fprintf(buf, "        resetter.Reset()\n")
			fmt.Fprintf(buf, "    }\n")
		}

	case *ast.StarExpr:
		// Указатель
		switch inner := expr.X.(type) {
		case *ast.Ident:
			// Указатель на базовый тип
			switch inner.Name {
			case "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"float32", "float64", "complex64", "complex128",
				"string", "bool", "byte", "rune":
				fmt.Fprintf(buf, "    if %s != nil {\n", fieldAccess)
				fmt.Fprintf(buf, "        *%s = %s\n", fieldAccess, getZeroValue(inner.Name))
				fmt.Fprintf(buf, "    }\n")
			default:
				// Указатель на структуру
				fmt.Fprintf(buf, "    if %s != nil {\n", fieldAccess)
				fmt.Fprintf(buf, "        if resetter, ok := interface{ Reset() }(%s); ok {\n", fieldAccess)
				fmt.Fprintf(buf, "            resetter.Reset()\n")
				fmt.Fprintf(buf, "        }\n")
				fmt.Fprintf(buf, "    }\n")
			}
		case *ast.SelectorExpr:
			// Указатель на импортированный тип
			fmt.Fprintf(buf, "    if %s != nil {\n", fieldAccess)
			fmt.Fprintf(buf, "        if resetter, ok := interface{ Reset() }(%s); ok {\n", fieldAccess)
			fmt.Fprintf(buf, "            resetter.Reset()\n")
			fmt.Fprintf(buf, "        }\n")
			fmt.Fprintf(buf, "    }\n")
		}

	case *ast.ArrayType:
		if expr.Len == nil {
			// Слайс
			fmt.Fprintf(buf, "    %s = %s[:0]\n", fieldAccess, fieldAccess)
		} else {
			// Массив - не сбрасываем, так как имеет фиксированный размер
			// Можно было бы установить нулевые значения, но оставляем как есть
			fmt.Fprintf(buf, "    // %s is array, skipping reset\n", fieldAccess)
		}

	case *ast.MapType:
		fmt.Fprintf(buf, "    clear(%s)\n", fieldAccess)

	case *ast.SelectorExpr:
		// Импортированный тип
		fmt.Fprintf(buf, "    // %s is imported type, checking for Reset method\n", fieldAccess)
		fmt.Fprintf(buf, "    if resetter, ok := interface{ Reset() }(&%s); ok {\n", fieldAccess)
		fmt.Fprintf(buf, "        resetter.Reset()\n")
		fmt.Fprintf(buf, "    }\n")

	default:
		// Для неизвестных типов просто оставляем комментарий
		fmt.Fprintf(buf, "    // %s: type %T not fully supported\n", fieldAccess, expr)
	}
}

func getZeroValue(typeName string) string {
	switch typeName {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune":
		return "0"
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return "nil"
	}
}
